#!/usr/bin/zsh

# FIXME: What do these do?

bindkey -e
bindkey "^[[H" beginning-of-line
bindkey "^[[7~" beginning-of-line
bindkey "^[[F" end-of-line
bindkey "^[[8~" end-of-line
bindkey "^[[3~" delete-char
